### ISSUE TITLE
Picture crop and resize don't apply in order.

### ISSUE THREAD

**Issue by zaddok** [jeffersoncbd/image-builder#3]
The image drawing code inside the library always applies the crop and resize in the same order, regardless of whether the crop() and/or resize() method was called on the picture first. This causes unexpected behavior due to changing the math that is needed.

**Comment by jeffersoncbd** [comment]
Was this problem resolved in the #2 ?

**Comment by jeffersoncbd** [comment]
Was this problem resolved in the PR #2 ?

**Comment by scripturial** [comment]
I changed the order it renders in my own personal branch. It seems like that change was approved by you. So it fixed it for me for now. I am not sure of a good way to allow the person calling the API to choose the order. Lets just close this for now.

**Comment by jeffersoncbd** [comment]
I remember trying to resolve the issue with the order of execution of these functions, but probably due to a lack of technical knowledge, I wasn't able to.
